---
title: "Coding Club"
output:
  html_document:
    self_contained: no
    toc: no
    toc_depth: 2
    code_folding: show
    toc_float: 
      collapsed: false
    number_sections: false
---

We will be building a Buzzfeed-style Quiz app using Shiny. This page will document our progress.

Coding club is meant to build coding skills in R, HTML, CSS, and JavaScript. You don't need to have any experience apart from basic R. If you can complete the [intro shiny tutorial](01-first-app.html) then you should be fine.



## 1. Setting Up the Framework 

2021-03-17 14:00 (Europe/London)

1. Check out the [demo app](https://shiny.psy.gla.ac.uk/debruine/coding_club/)
1. Download the [template](https://github.com/debruine/shiny_template)
1. You can access the code for the final app at <https://github.com/PsyTeachR/shiny-tutorials/tree/master/coding_club>

In this first session, we:

* discussed the structure of a shiny app 
* edited the main tab to have a collapsible box for each question 
* added six custom image buttons for the first question
* wrote a function to more easily set up a custom image button
* edited the www/custom.css file to remove the background and padding from the custom image buttons

To prep for the next meeting, I'd like you to:

* decide what your quiz theme and questions will be
* find images for each question ([Pixabay](https://pixabay.com) is a good site for open-access images)
* set up a few questions with image buttons
* Edit the info tab to include image citation information

The password for the [session recording](https://uofglasgow.zoom.us/rec/share/lTH8SniBrkm3PilcTG0I0_KlSNqVnWNelq_4A5vE-VQ9h9_IECoNHjfdo30of_q9.0UOkISRJLtYCX0wA) is on the coding club channel of the Methods and MetaScience Team. Contact Lisa to be added if you're at Glasgow, or to ask for the password if you're not.

You can download a zip file with the [code for our current progress](files/quiz1.zip).

## 2. Button Actions

2021-03-31 14:00 (Europe/London)

In this second session, we:

* used CSS to set the style of selected and unselected buttons
* used `observeEvent()` to change the style of buttons when clicking on them
* wrote a custom function to do this for all image buttons, using their question number and colour name

To prep for the next meeting, I'd just like you to:

* get your app caught up to the same place we left off (all image buttons displaying the correct outlines when you click on them)
* try out a few other input options for the final question, like [`selectInput()`](https://shiny.rstudio.com/reference/shiny/1.6.0/selectInput.html), 
[`radioButtons()`](https://shiny.rstudio.com/reference/shiny/1.6.0/radioButtons.html), 
[`textInput()`](https://shiny.rstudio.com/reference/shiny/1.6.0/textInput.html), or
[`sliderInput()`](https://shiny.rstudio.com/reference/shiny/1.6.0/sliderInput.html).

Resources:

* [session recording](https://uofglasgow.zoom.us/rec/share/PAjIgwcdRBVNATStImFEeLQzmg3m6YGxjYZ8_Y3kjh1bYGPoeDVQvBDrOc4vzi3q.sHHPrI5czz3904RM)
* zip file with the [code for our current progress](files/quiz2.zip)

## 3. Outputs

2021-04-14 14:00 (Europe/London)

In this third session, we:

* updated the custom function `Q()` to close the current question box and open the next one
* created a new feedback tab and added it to the UI
* used `observeEvent()` to respond to clicking the submit button
* used `reactiveValues()` to create values for saving the image button answers and plot
* made a feedback plot with `outputPlot()` and `renderPlot()` that creates a plot from the quiz answers

To prep for the next meeting, I'd like you to:

* make your feedback plot nicer, especially thinking about font sizes
* if you want further challenge, add feedback text in addition to the plot using `textOutput()` and `renderText()`

Resources:

* [session recording](https://uofglasgow.zoom.us/rec/share/hFnvznxyycp41nc6vCjGNXFA0W39s2yLQ3AikPlyXXCJP3LorWtzsE1jW90COms.4D1tvi9ZqlnX25wf)
* zip file with the [code for our current progress](files/quiz3.zip)

## 4. Saving Data

2021-04-28 14:00 (Europe/London)

In this fourth session, we:

* Added a button to allow participants to save their data
* added conditional properties so the button could only be used once, after the quiz was completed
* Learned to save data in a CSV file
* Read the full data from the saved file and created a feedback visualisation
* Discussed pros and cons of local storage of saved data

Resources:

* [session recording](https://uofglasgow.zoom.us/rec/share/gNGYoC65CziY_pcmEi03PXCwbu30bLueCKkJOuiK5qzqdgNxQGQmMhFGbPUyItJR.Rkivv76FW8oDwR7a)
* [persistent data storage in Shiny](https://shiny.rstudio.com/articles/persistent-data-storage.html)
* zip file with the [code for our final progress](files/quiz4.zip)

## 5. TBA

2021-05-12 14:00 (Europe/London)
